const fortunes = [
    "You're about to discover your next favorite song 🎶",
    "A golden retriever is thinking about you 🐶",
    "Your next coffee will be life-changing ☕",
    "The universe says, 'Go for it!' 🚀",
    "An unexpected meme will make you laugh today 😂",
    "Someone is low-key admiring your vibe 👀",
    "Big 'main character energy' coming your way 💫",
    "A new adventure is waiting... check your DMs 🌄",
    "You're about to have an epiphany while scrolling 🧠",
    "The algorithm loves you 💻💖",
    "You're about to meet someone amazing today! 😎",
    "A fortune cookie is about to change your life. 🍪",
    "Your next snack will be extraordinary! 🍩",
    "The stars align for you today. ✨",
    "A new meme will brighten your day! 📱",
    "Someone is going to text you something hilarious! 😂",
    "The weekend holds unexpected fun. 🎉",
    "A good playlist is coming your way soon. 🎧",
    "You will soon find the perfect pair of socks. 🧦",
    "Prepare for a totally awesome new trend. 😎",
    "A small act of kindness will come your way. 💖",
    "Your favorite movie is about to become your new obsession. 🎬",
    "You're on the verge of discovering a hidden talent. 🎨",
    "Someone is going to surprise you with an unexpected gift. 🎁",
    "Your next meal will be your favorite food. 🍕",
    "A surprise compliment is coming your way. 💌",
    "The perfect day is just around the corner. 🌞",
    "A new friendship will brighten your day. 🤝",
    "You're about to see something that will blow your mind. 🤯",
    "Your next adventure will take you to a place you never imagined. 🌍",
    "Your vibe attracts the right people. ✨",
    "Today will be filled with laughter and fun. 😄",
    "You're going to have an amazing hair day soon. 💇‍♀️",
    "A wonderful surprise awaits you in your inbox. 📧",
    "You're about to create something unforgettable. 🖋️",
    "You will soon make a new connection that will be life-changing. 🔗",
    "Something you've been waiting for is just about to arrive. ⏳",
    "A fun weekend trip is on the horizon. 🏖️",
    "The perfect outfit is waiting for you. 👗",
    "Your creativity is about to hit an all-time high. 🎨",
    "Someone is about to share a secret with you. 🤐",
    "Get ready for a wave of positive energy. 🌊",
    "The universe is about to reward your hard work. 💪",
    "Something wonderful is about to happen. 🌟",
    "You're about to meet someone who will inspire you. 🌈",
    "The next chapter of your life is going to be exciting. 📖",
    "Prepare for a moment of pure happiness today. 😊",
    "A fun surprise is waiting for you. 🎉",
    "You're about to discover something new about yourself. 🕵️‍♀️",
    "A new opportunity will soon present itself. 🌟",
    "You're about to get some amazing news. 📰",
    "Something small today will lead to something big tomorrow. 🌱",
    "You're about to make a positive impact on someone's life. 🌍",
    "You're about to make a decision that will change everything. ⚡",
    "The universe has something special planned for you. 🎁",
    "Someone will soon appreciate you in a big way. 🙏",
    "A new hobby is going to bring you joy. 🎮",
    "Good things are coming your way. 🌟",
    "Your next date will be unforgettable. 💕",
    "You're going to see something beautiful today. 🌺",
    "Your creativity will lead to something amazing. 🎨",
    "Something you’ve been thinking about will soon come to life. 💭",
    "Your dreams are about to align with reality. 🌌",
    "You're about to receive a sign that will change everything. 🔮",
    "The best is yet to come. 🌟",
    "Something unexpected will bring you joy today. 🎉",
    "You're about to discover a new favorite place. 🌆",
    "A random act of kindness will change your day. 💖",
    "You're about to have a productive and fulfilling day. 📅",
    "Your next adventure will lead you to something extraordinary. 🌍",
    "You're about to be pleasantly surprised by a coincidence. 🤯",
    "A message you’ve been waiting for is on the way. 📲",
    "Your efforts are about to be rewarded. 🏆",
    "You’re about to make a new connection that will last forever. 🫶",
    "A day of self-care is in your near future. 🛀",
    "You’re going to have an epic win today! 🏅",
    "The universe is sending you a sign of good fortune. ✨",
    "A random encounter will change your life. 💫",
    "You’re about to experience a breakthrough moment. 🧠",
    "Someone is about to give you the best advice. 🗣️",
    "A moment of peace and calm is coming your way. 🕊️",
    "An unexpected act of kindness is coming your way. 🤗",
    "Something small will lead to something great today. 🪙",
    "The world is about to open up in exciting ways for you. 🌎",
    "A moment of inspiration is just around the corner. 💡",
    "Your next step will lead to great success. 🚀",
    "You're about to have a 'wow' moment today. 😲",
    "A new challenge will soon lead you to victory. 🏆",
    "You're going to create something unforgettable soon. 🖌️",
    "A funny surprise is coming your way. 😆",
    "You're about to embark on an incredible journey. 🌄",
    "Your confidence is about to reach new heights. 🦸‍♀️",
    "The perfect time to take a risk is right now. ⏰",
    "You're about to be part of something big. 🌟",
    "An unexpected opportunity will open up for you. 🚪",
    "A moment of clarity is coming your way. 🔍",
    "You’re about to receive an unexpected compliment. 💬",
    "A hidden talent is about to be revealed. 🎤",
    "You're going to shine in a new way today. ✨",
    "A wave of motivation is heading your way. 💥",
    "Your passion is about to pay off. 🔥",
    "You’re going to discover something amazing about yourself. 🧭",
    "Your next big idea is going to change everything. 💡",
    "A new chapter in your life is about to begin. 📚",
    "Someone is going to brighten your day with kindness. 🌸",
    "Get ready for some epic news today. 🗞️",
    "A small decision today will lead to big rewards. 🏅",
    "You're about to experience something totally new and exciting. 🔮",
    "The universe has something special planned for you. 🌟",
    "An exciting journey is about to begin. ✈️",
    "You’re about to experience a life-changing moment. ⚡",
    "Something great is going to happen today. 🎉",
    "Your dreams are about to take flight. 🦋",
    "You’re about to meet someone amazing. 🌟",
    "A surprise awaits you today. 🎁",
    "You're about to hit a milestone you didn’t expect. 🎯",
    "An exciting change is just around the corner. 🔄",
    "A perfect opportunity is about to present itself. 🌅",
    "The perfect day is ahead of you. 🌞",
    "A meaningful connection is on its way to you. 🤝",
    "You are about to get some amazing news. 📰",
    "A new favorite hobby is about to take over your life. 🧶",
    "You’ll find the perfect song that matches your mood soon. 🎵",
    "Your positive attitude is attracting great things. ✨",
    "You're about to discover your new favorite book. 📚",
    "Something exciting is going to happen when you least expect it. 🕒",
    "Your next project is going to be a huge success. 🖥️",
    "A new friendship is about to bloom. 🌻",
    "You're about to achieve something you've worked so hard for. 🎉",
    "A random act of kindness will restore your faith in humanity. 🙌",
    "A perfect moment is coming your way soon. 💖",
    "You're about to get some well-deserved recognition. 🏅",
    "The universe is aligning to give you exactly what you need. ✨",
    "You're about to experience a burst of creative energy. 🎨",
    "A small change today will lead to big results tomorrow. ⚡",
    "You will soon be in the right place at the right time. 🕰️",
    "You're about to have an 'aha' moment. 💡",
    "Your next adventure will be one to remember. 🌟",
    "The universe is sending you a sign. Look closely! 👀",
    "You're about to meet someone who will change everything. 💫",
    "Something you love is about to make a comeback. 🎤",
    "You're about to step into your power. ⚡",
    "A fun day is ahead of you. 🎈",
    "You're about to get the answer you've been looking for. 🧩",
    "Someone is about to make your day with something thoughtful. 🌻",
    "The universe is ready to send you good vibes. ✨",
    "You're about to discover something that will change your life. 🧭",
    "Prepare for a wonderful surprise soon. 🎉",
    "You're about to see your efforts come to fruition. 🌱",
    "Something you’ve been wishing for is about to happen. 🌠",
    "Your next step is going to lead to something amazing. 🚶‍♀️",
];


const challenges = [
    "Compliment a stranger today!",
    "Take a 10-minute walk and enjoy nature.",
    "Write down three things you’re grateful for.",
    "Try something new for lunch.",
    "Spend 5 minutes meditating.",
    "Smile at everyone you meet today.",
    "Read for 15 minutes before bed.",
    "Dance for 5 minutes to your favorite song.",
    "Send a message to someone you haven’t talked to in a while.",
    "Write a handwritten note to someone you appreciate.",
    "Spend 10 minutes organizing your workspace.",
    "Take a deep breath and stretch your body every hour.",
    "Try a new hobby you’ve always wanted to explore.",
    "Take a break from social media for an hour.",
    "Go for a walk without your phone.",
    "Drink an extra glass of water today.",
    "Cook a new recipe for dinner.",
    "Start your day with a positive affirmation.",
    "Reach out to someone you care about just to check in.",
    "Practice gratitude by writing a thank-you note to someone.",
    "Do a random act of kindness for someone.",
    "Spend 10 minutes listening to a podcast you find interesting.",
    "Make a list of goals you want to achieve this month.",
    "Do a creative activity like drawing, writing, or crafting.",
    "Take a 5-minute mindfulness break during work.",
    "Unsubscribe from an email list that no longer serves you.",
    "Set a timer for 15 minutes and tidy up your space.",
    "Compliment yourself in the mirror today.",
    "Give yourself permission to take a nap if you need it.",
    "Try a new type of workout or exercise.",
    "Make a vision board for your goals and dreams.",
    "Send an encouraging text to someone who needs it.",
    "Take a moment to appreciate the beauty around you.",
    "Try a new self-care routine tonight.",
    "Write a short poem or create a piece of art.",
    "Take a social media detox for the day.",
    "Set aside 30 minutes for focused work without distractions.",
    "Go on a photo walk and capture something beautiful.",
    "Try a new type of tea or coffee you’ve never had before.",
    "Plan a mini weekend adventure or day trip.",
    "Start your day without looking at your phone.",
    "Set a new fitness goal for the week and work towards it.",
    "Send a thank-you message to someone who helped you recently.",
    "Spend 10 minutes reflecting on your achievements this year.",
    "Try journaling for 10 minutes a day for a week.",
    "Clear out one drawer or closet in your home.",
    "Practice deep breathing exercises when you feel stressed.",
    "Wake up 15 minutes earlier to start your day calmly.",
    "Do something creative that’s outside of your normal routine.",
    "Call a friend or family member you haven’t spoken to in a while.",
    "Give yourself a mini spa treatment at home.",
    "Watch the sunrise or sunset today.",
    "Write a letter to your future self.",
    "Take 5 minutes to appreciate where you are in life right now.",
    "Spend time in silence for 10 minutes to clear your mind.",
    "Give yourself a compliment every morning this week.",
    "Practice mindful eating today—really focus on each bite.",
    "Take a break from multitasking and focus on one thing at a time.",
    "Spend 10 minutes outside in the fresh air.",
    "Get creative and try making something from scratch.",
    "Try a new workout or yoga pose today.",
    "Do something spontaneous that makes you happy.",
    "Dedicate an hour today to just being present and enjoying the moment.",
    "Write down one thing you’ve learned today.",
    "Find a quiet spot and do absolutely nothing for 10 minutes.",
    "Reflect on something you’re proud of yourself for.",
    "Watch a documentary or read an article about something new.",
    "Send a positive message to a coworker or friend.",
    "Take 15 minutes to declutter your living space.",
    "Try a new type of cuisine for dinner tonight.",
    "Write down your dreams and goals for the next year.",
    "Go a full day without complaining.",
    "Share an inspiring quote with someone who needs it.",
    "Spend an afternoon with a hobby you love.",
    "Commit to walking or biking somewhere instead of driving.",
    "Clean out your email inbox and delete old messages.",
    "Practice self-compassion and forgive yourself for something.",
    "Take 5 minutes to stretch your body before you go to sleep.",
    "Set a goal to drink more water today.",
    "Try a 10-minute guided meditation.",
    "Do one thing today that scares you, even if it’s small.",
    "Take a moment to unplug and enjoy some quiet time.",
    "Give someone a genuine compliment.",
    "Try to be fully present when talking to someone today.",
    "Make a list of things that bring you peace.",
    "Do something kind for someone, expecting nothing in return.",
    "Give yourself permission to take a mental health day if needed.",
    "Challenge yourself to laugh or smile more today.",
    "Make time for a creative project you’ve been putting off.",
    "Walk or cycle somewhere you’ve never been before.",
    "Listen to an audiobook or podcast during your commute.",
    "Practice positive self-talk for the next hour.",
    "Spend time with an animal (yours or a friend’s).",
    "Try a new skincare routine for the week.",
    "Give up one bad habit for the day.",
    "Spend time organizing something that needs it.",
    "Try a new workout routine or fitness class.",
    "Take a nap or rest for 15 minutes during the day.",
    "Create a gratitude jar where you add something daily.",
    "Share a random act of kindness with a stranger.",
    "Do something creative with your hands today.",
    "Go a full day without social media.",
    "Write a thank-you note to someone who’s made an impact in your life.",
    "Practice deep breathing for 5 minutes when you feel overwhelmed.",
    "Start a new book or finish one you’ve started.",
    "Find a quiet place to reflect for 10 minutes.",
    "Rearrange your furniture or redecorate a small area.",
    "Turn off all screens for an hour and do something offline.",
    "Watch an inspiring TED Talk or video today.",
    "Try a new hobby that you've always wanted to try.",
    "Compliment yourself every day for the next week.",
    "Plan a mini self-care day at home.",
    "Clean out your purse or wallet and organize it.",
    "Start a 30-day gratitude challenge.",
    "Take a long walk and clear your mind.",
    "Try a 5-minute breathing exercise before bed.",
    "Create a playlist of songs that make you feel good.",
    "Try a new type of workout, like pilates or swimming.",
    "Use a daily planner or bullet journal to organize your thoughts.",
    "Spend a day without checking your phone constantly.",
    "Reconnect with a friend or family member you haven’t seen in a while.",
    "Dedicate 20 minutes to a hobby you enjoy.",
    "Read an inspiring book or article about personal growth.",
    "Take 10 minutes to enjoy a favorite childhood activity.",
    "Learn something new today, even if it’s just a small fact.",
    "Set a timer and do a focused work sprint for 25 minutes.",
    "Make a list of things you love about yourself.",
    "Do a quick workout every morning for the next 7 days.",
    "Take a mental health day to relax and recharge.",
    "Spend 15 minutes organizing your phone or computer files.",
    "Do something you’ve always been putting off.",
    "Give yourself a small treat for completing a challenge.",
    "Start a new journaling practice or daily reflection.",
    "Take time today to check in with your mental health.",
    "Give yourself a digital detox for the evening.",
    "Practice saying no to something you don’t want to do.",
    "Look at yourself in the mirror and give yourself a compliment.",
    "Take 5 minutes today to think about your long-term goals.",
    "Declutter one area of your home today.",
    "Start a new habit by committing to it every day for a week.",
    "Go to bed 30 minutes earlier than usual for a restful night’s sleep.",
    "Spend time with someone who makes you feel good.",
    "Take 10 minutes to meditate before bed.",
    "Laugh out loud at something that makes you happy.",
    "Try a new hobby or interest to expand your horizons.",
    "Start a gratitude journal and write down one thing you’re grateful for each day.",
    "Give yourself permission to take a break when you need it.",
    "Try a new restaurant or coffee shop you haven’t been to before.",
    "Spend 10 minutes planning something fun for the weekend.",
    "Learn something new about a culture different from your own.",
    "Set aside time each day for a quiet moment of reflection.",
    "Try eating more fruits and vegetables today.",
    "Watch a documentary about something you’re curious about.",
    "Take a day to focus on kindness and positivity.",
    "Write down a list of things that make you feel at peace.",
    "Start your day with a cup of tea or coffee and enjoy the moment.",
    "Do something spontaneous that makes you happy."
];
