const fortunes = [
    "You're about to discover your next favorite song 🎶",
    "A golden retriever is thinking about you 🐶",
    "Your next coffee will be life-changing ☕",
    "The universe says, 'Go for it!' 🚀",
    "An unexpected meme will make you laugh today 😂",
    "Someone is low-key admiring your vibe 👀",
    "Big 'main character energy' coming your way 💫",
    "A new adventure is waiting... check your DMs 🌄",
    "You're about to have an epiphany while scrolling 🧠",
    "The algorithm loves you 💻💖",
    "You're about to meet someone amazing today! 😎",
    "A fortune cookie is about to change your life. 🍪",
    "Your next snack will be extraordinary! 🍩",
    "The stars align for you today. ✨",
    "A new meme will brighten your day! 📱",
    "Someone is going to text you something hilarious! 😂",
    "The weekend holds unexpected fun. 🎉",
    "A good playlist is coming your way soon. 🎧",
    "You will soon find the perfect pair of socks. 🧦",
    "Prepare for a totally awesome new trend. 😎",
    "A small act of kindness will come your way. 💖",
    "Your favorite movie is about to become your new obsession. 🎬",
    "You're on the verge of discovering a hidden talent. 🎨",
    "Someone is going to surprise you with an unexpected gift. 🎁",
    "Your next meal will be your favorite food. 🍕",
    "A surprise compliment is coming your way. 💌",
    "The perfect day is just around the corner. 🌞",
    "A new friendship will brighten your day. 🤝",
    "You're about to see something that will blow your mind. 🤯",
    "Your next adventure will take you to a place you never imagined. 🌍",
    "Your vibe attracts the right people. ✨",
    "Today will be filled with laughter and fun. 😄",
    "You're going to have an amazing hair day soon. 💇‍♀️",
    "A wonderful surprise awaits you in your inbox. 📧",
    "You're about to create something unforgettable. 🖋️",
    "You will soon make a new connection that will be life-changing. 🔗",
    "Something you've been waiting for is just about to arrive. ⏳",
    "A fun weekend trip is on the horizon. 🏖️",
    "The perfect outfit is waiting for you. 👗",
    "Your creativity is about to hit an all-time high. 🎨",
    "Someone is about to share a secret with you. 🤐",
    "Get ready for a wave of positive energy. 🌊",
    "The universe is about to reward your hard work. 💪",
    "Something wonderful is about to happen. 🌟",
    "You're about to meet someone who will inspire you. 🌈",
    "The next chapter of your life is going to be exciting. 📖",
    "Prepare for a moment of pure happiness today. 😊",
    "A fun surprise is waiting for you. 🎉",
    "You're about to discover something new about yourself. 🕵️‍♀️",
    "A new opportunity will soon present itself. 🌟",
    "You're about to get some amazing news. 📰",
    "Something small today will lead to something big tomorrow. 🌱",
    "You're about to make a positive impact on someone's life. 🌍",
    "You're about to make a decision that will change everything. ⚡",
    "The universe has something special planned for you. 🎁",
    "Someone will soon appreciate you in a big way. 🙏",
    "A new hobby is going to bring you joy. 🎮",
    "Good things are coming your way. 🌟",
    "Your next date will be unforgettable. 💕",
    "You're going to see something beautiful today. 🌺",
    "Your creativity will lead to something amazing. 🎨",
    "Something you’ve been thinking about will soon come to life. 💭",
    "Your dreams are about to align with reality. 🌌",
    "You're about to receive a sign that will change everything. 🔮",
    "The best is yet to come. 🌟",
    "Something unexpected will bring you joy today. 🎉",
    "You're about to discover a new favorite place. 🌆",
    "A random act of kindness will change your day. 💖",
    "You're about to have a productive and fulfilling day. 📅",
    "Your next adventure will lead you to something extraordinary. 🌍",
    "You're about to be pleasantly surprised by a coincidence. 🤯",
    "A message you’ve been waiting for is on the way. 📲",
    "Your efforts are about to be rewarded. 🏆",
    "You’re about to make a new connection that will last forever. 🫶",
    "A day of self-care is in your near future. 🛀",
    "You’re going to have an epic win today! 🏅",
    "The universe is sending you a sign of good fortune. ✨",
    "A random encounter will change your life. 💫",
    "You’re about to experience a breakthrough moment. 🧠",
    "Someone is about to give you the best advice. 🗣️",
    "A moment of peace and calm is coming your way. 🕊️",
    "An unexpected act of kindness is coming your way. 🤗",
    "Something small will lead to something great today. 🪙",
    "The world is about to open up in exciting ways for you. 🌎",
    "A moment of inspiration is just around the corner. 💡",
    "Your next step will lead to great success. 🚀",
    "You're about to have a 'wow' moment today. 😲",
    "A new challenge will soon lead you to victory. 🏆",
    "You're going to create something unforgettable soon. 🖌️",
    "A funny surprise is coming your way. 😆",
    "You're about to embark on an incredible journey. 🌄",
    "Your confidence is about to reach new heights. 🦸‍♀️",
    "The perfect time to take a risk is right now. ⏰",
    "You're about to be part of something big. 🌟",
    "An unexpected opportunity will open up for you. 🚪",
    "A moment of clarity is coming your way. 🔍",
    "You’re about to receive an unexpected compliment. 💬",
    "A hidden talent is about to be revealed. 🎤",
    "You're going to shine in a new way today. ✨",
    "A wave of motivation is heading your way. 💥",
    "Your passion is about to pay off. 🔥",
    "You’re going to discover something amazing about yourself. 🧭",
    "Your next big idea is going to change everything. 💡",
    "A new chapter in your life is about to begin. 📚",
    "Someone is going to brighten your day with kindness. 🌸",
    "Get ready for some epic news today. 🗞️",
    "A small decision today will lead to big rewards. 🏅",
    "You're about to experience something totally new and exciting. 🔮",
    "The universe has something special planned for you. 🌟",
    "An exciting journey is about to begin. ✈️",
    "You’re about to experience a life-changing moment. ⚡",
    "Something great is going to happen today. 🎉",
    "Your dreams are about to take flight. 🦋",
    "You’re about to meet someone amazing. 🌟",
    "A surprise awaits you today. 🎁",
    "You're about to hit a milestone you didn’t expect. 🎯",
    "An exciting change is just around the corner. 🔄",
    "A perfect opportunity is about to present itself. 🌅",
    "The perfect day is ahead of you. 🌞",
    "A meaningful connection is on its way to you. 🤝",
    "You are about to get some amazing news. 📰",
    "A new favorite hobby is about to take over your life. 🧶",
    "You’ll find the perfect song that matches your mood soon. 🎵",
    "Your positive attitude is attracting great things. ✨",
    "You're about to discover your new favorite book. 📚",
    "Something exciting is going to happen when you least expect it. 🕒",
    "Your next project is going to be a huge success. 🖥️",
    "A new friendship is about to bloom. 🌻",
    "You're about to achieve something you've worked so hard for. 🎉",
    "A random act of kindness will restore your faith in humanity. 🙌",
    "A perfect moment is coming your way soon. 💖",
    "You're about to get some well-deserved recognition. 🏅",
    "The universe is aligning to give you exactly what you need. ✨",
    "You're about to experience a burst of creative energy. 🎨",
    "A small change today will lead to big results tomorrow. ⚡",
    "You will soon be in the right place at the right time. 🕰️",
    "You're about to have an 'aha' moment. 💡",
    "Your next adventure will be one to remember. 🌟",
    "The universe is sending you a sign. Look closely! 👀",
    "You're about to meet someone who will change everything. 💫",
    "Something you love is about to make a comeback. 🎤",
    "You're about to step into your power. ⚡",
    "A fun day is ahead of you. 🎈",
    "You're about to get the answer you've been looking for. 🧩",
    "Someone is about to make your day with something thoughtful. 🌻",
    "The universe is ready to send you good vibes. ✨",
    "You're about to discover something that will change your life. 🧭",
    "Prepare for a wonderful surprise soon. 🎉",
    "You're about to see your efforts come to fruition. 🌱",
    "Something you’ve been wishing for is about to happen. 🌠",
    "Your next step is going to lead to something amazing. 🚶‍♀️",
];


function generateFortune() {
    const randomIndex = Math.floor(Math.random() * fortunes.length);
    const fortune = fortunes[randomIndex];
    document.getElementById("fortune-text").innerText = fortune;

    // Optional: Add a little shake effect to the cookie
    const cookieImage = document.getElementById("cookie");
    cookieImage.classList.add("shake");

    // Remove the shake effect after animation ends
    setTimeout(() => {
        cookieImage.classList.remove("shake");
    }, 500);
}
